import React from 'react';
import { Button } from '@repo/ui';
import { AllocationProposal } from '@repo/types';

interface ProposedTeamPanelProps {
  proposal: AllocationProposal | null;
  onEditRequirements: () => void;
  allocationSource: 'FORM' | 'AI';
  onApprove?: () => void;
  onDiscard?: () => void;
  onEditAllocation?: () => void;
  onUndo?: () => void;
  canUndo?: boolean;
}

export default function ProposedTeamPanel({
  proposal,
  onEditRequirements,
  allocationSource,
  onApprove,
  onDiscard,
  onEditAllocation,
  onUndo,
  canUndo = false,
}: ProposedTeamPanelProps) {
  return (
    <div className="flex flex-col h-full bg-white rounded-lg shadow p-6">
      <div className="flex justify-between items-center mb-4">
        <div className="flex items-center gap-3">
          <h2 className="text-xl font-bold text-gray-900">
            Proposed Team for {proposal?.projectName}
          </h2>
          {allocationSource === 'AI' && (
            <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800 animate-pulse">
              ✨ Generated by AI
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          {onUndo && (
            <Button
              variant="outline"
              onClick={onUndo}
              disabled={!canUndo}
              className="text-sm"
            >
              Undo last AI change
            </Button>
          )}
          <Button
            variant="secondary"
            onClick={onEditRequirements}
            className="text-sm border border-gray-300 bg-white hover:bg-gray-50 text-gray-700"
          >
            Edit Requirements
          </Button>
        </div>
      </div>

      {proposal ? (
        <div className="mt-0 transition-opacity duration-500 ease-in-out h-full overflow-auto flex flex-col">
          <div className="overflow-hidden sm:rounded-md flex-1">
            <ul className="divide-y divide-gray-200">
              {(proposal.roleAllocations?.length > 0 &&
                proposal?.roleAllocations?.flatMap((role, roleIdx) =>
                  role.recommendations.map((rec, recIdx) => (
                    <li
                      key={`${roleIdx}-${recIdx}`}
                      className="px-6 py-4 flex flex-col gap-2 hover:bg-gray-50 border-b last:border-0"
                    >
                      <div className="flex justify-between items-center">
                        <div className="flex items-center">
                          <span className="h-8 w-8 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold mr-3">
                            {rec.employeeName.charAt(0)}
                          </span>
                          <div>
                            <p className="text-sm font-medium text-indigo-600">
                              {rec.employeeName}
                            </p>
                            <p className="text-xs text-gray-500">
                              {role.roleName}
                            </p>
                          </div>
                        </div>
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                          {Math.round(rec.confidence * 100)}% Match
                        </span>
                      </div>
                      <p className="text-sm text-gray-600 mt-2 bg-gray-50 p-2 rounded border border-gray-100">
                        {rec.reason}
                      </p>
                    </li>
                  )),
                )) ??
                null}
            </ul>
          </div>

          {/* Action Footer */}
          <div className="mt-6 pt-4 border-t border-gray-200 flex gap-3 justify-end">
            <button
              onClick={onDiscard}
              className="flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors shadow-sm text-sm font-medium"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
              Clear
            </button>
            <button
              onClick={onEditAllocation}
              className="flex items-center gap-2 px-4 py-2 bg-white text-gray-900 border border-black rounded-md hover:bg-gray-50 transition-colors shadow-sm text-sm font-medium"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"
                />
              </svg>
              Edit
            </button>
            <button
              onClick={onApprove}
              className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors shadow-sm text-sm font-medium"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
              Approve
            </button>
          </div>
        </div>
      ) : (
        <div className="flex items-center justify-center h-full text-gray-400">
          No allocation data found.
        </div>
      )}
    </div>
  );
}
